# Generated by Django 5.2 on 2025-05-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mqttmessage',
            name='cyclecount',
            field=models.CharField(default=11, max_length=200),
            preserve_default=False,
        ),
    ]
