# Generated by Django 5.0.6 on 2025-06-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mqttmessage',
            name='cyclecount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
