# Generated by Django 4.2.9 on 2025-06-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='color_image',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='thermal_image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
