# Generated by Django 5.2 on 2025-05-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_mqttmessage_cyclecount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mqttmessage',
            name='device_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
