# Generated by Django 5.0.6 on 2025-06-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_mqttmessage_cyclecount'),
    ]

    operations = [
        migrations.AddField(
            model_name='mqttmessage',
            name='cycle_status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
