# Generated by Django 4.2.9 on 2025-07-10 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_cycle_color_image_alter_cycle_thermal_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('Device_id', models.CharField(primary_key=True, serialize=False)),
                ('User_name', models.CharField(max_length=30)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('Mob', models.BigIntegerField(unique=True)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
