# Generated by Django 5.0.6 on 2025-06-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_mqttmessage_cycle_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='cyclecount',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
