# Generated by Django 5.2 on 2025-05-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_mqttmessage_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mqttmessage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
