# Generated by Django 5.2 on 2025-06-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_cycle_cyclecount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mqttmessage',
            name='cycle_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
