# Generated by Django 4.2.9 on 2025-08-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_scheduling'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduling',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
