# Generated by Django 5.2 on 2025-05-29 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_mqttmessage_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mqttmessage',
            name='cyclecount',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mqttmessage',
            name='device_id',
            field=models.CharField(db_index=True, default=11, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mqttmessage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mqttmessage',
            name='payload',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mqttmessage',
            name='topic',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
