# Generated by Django 4.2.9 on 2025-08-11 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_scheduling_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduling',
            name='is_running',
            field=models.BooleanField(default=False),
        ),
    ]
