# Generated by Django 5.2 on 2025-05-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_mqttmessage_cyclecount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mqttmessage',
            name='cycle_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='mqttmessage',
            name='cyclecount',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
