# Generated by Django 5.1.5 on 2025-08-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_scheduling_is_running'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduling',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
