# Generated by Django 5.2 on 2025-05-30 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_mqttmessage_cycle_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mqttmessage',
            old_name='payload',
            new_name='weight_final',
        ),
        migrations.AddField(
            model_name='mqttmessage',
            name='weight_intial',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
